# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9ebc0c99c1b34cd5bb31e22b69b34451412f4d0195ae4b79cb1632997fb8fb9bbfe99a440aa4b43e08a273c9b8872be3603fef55a6a4c292ad9b9968ed6d521

test:
  secret_key_base: b487ee442d74fbcdb09d751fbabbcef32da20c278e7ecd5ee92629879206aba2f456130c3e6c8c6e8da90ca3af32d3a06f5f2c92d4aeba33a72d673871a96c13

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 0af436b1e19184ff0f514544d03b1cc7fb863ef579e174e38db645be53ffebfc8e2ea55ed625e987b0e8dda5f446bfb8f9eec1fb5e1cbe10b1296685e4d4f3b9
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
